### ISSUE TITLE
11.1.0 Old3DS USA pidf.dmp file 

### ISSUE THREAD

**Issue by jaxrogers2** [astronautlevel2/BootNTR#1]
The link is here: https://drive.google.com/open?id=0B5iNZ1D1UhiNQ1RGNlZraDhwdlE

Ran the latest BootNTR cia from here on 11.1.0 USA old3DS with A9LH Luma Dev with an 11.0 firmware.bin dumped from Decrypt9 to get this.

**Comment by kelsom** [comment]
ok thx

**Comment by astronautlevel2** [comment]
Hey, thanks for submitting this, but I already added home menu support for all consoles - I should probably clarify that in the README :stuck_out_tongue: 

Closing this issue for now, thanks for the help, though!
