### ISSUE TITLE
[Question] Do you plan to release 11.2 support?

### ISSUE THREAD

**Issue by Carbuino** [astronautlevel2/BootNTR#4]
Refer to title ^

**Comment by DakotaKry** [comment]
Would like to add, I am using a 
Console: n3DSXL 
System Firm: 11.2.0-35U
A9LH: Yes
CFW: 6.3.1-b3e3a293 (dev)

Immediately regretted updating.

To me looks like its just failing the firmware check. Wish I could bypass it.

**Comment by astronautlevel2** [comment]
Yes, in fact it's already in the latest master commit. It should work if you compile it, but I want to personally test it before releasing anything.

**Comment by astronautlevel2** [comment]
Making release now.
